[theme]
base="light"

[client]
showErrorDetails = false
showSidebarNavigation = false
toolbarMode = "developer"

[global]
disableWidgetStateDuplicationWarning = true

[server]
runOnSave = true
maxUploadSize = 100

[browser]
gatherUsageStats=false
